#!/bin/bash

source ./var.sh

if [ "$1" -ne "$2" ] && [ "$3" -ne "$4" ]; then

FOREGROUND_NAME=$(( 30 + $(./case.sh $1) ))
BACKGROUND_NAME=$(( 40 + $(./case.sh $2) ))
FOREGROUND_VALUE=$(( 30 + $(./case.sh $3) ))
BACKGROUND_VALUE=$(( 40 + $(./case.sh $4) ))

echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mHOSTNAME[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$HOSTNAME[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mTIMEZONE[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$TIMEZONE[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mUSER[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$USER[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mOS[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$OS[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mDATE[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$DATE[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mUPTIME[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$UPTIME[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mUPTIME_SEC[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$UPTIME_SEC[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mIP[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$IP[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mMASK[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$MASK[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mGATEWAY[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$GATEWAY[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mRAM_TOTAL[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$RAM_TOTAL[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mRAM_USED[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$RAM_USED[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mRAM_FREE[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$RAM_FREE[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mSPACE_ROOT[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$SPACE_ROOT[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mSPACE_ROOT_USED[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$SPACE_ROOT_USED[0m"
echo -e "\e[${FOREGROUND_NAME};${BACKGROUND_NAME}mSPACE_ROOT_FREE[0m = \e[${FOREGROUND_VALUE};${BACKGROUND_VALUE}m$SPACE_ROOT_FREE[0m"

else echo "ERROR: Foreground and background colors can't be the same."

fi
